Ebury/chameleon

- src/components/ec-container/ec-container.story.js
- src/components/ec-navigation-link/ec-navigation-link.vue
- src/components/ec-user-info/ec-user-info.story.js
- src/components/ec-user-info/ec-user-info.vue
- src/scss/components/ec-btn/_ec-btn.scss
- src/scss/components/ec-btn/ec-btn.story.js
- src/scss/elements/_elements.scss
Non planned pr
Mostly:
*fixing some bug with the icons buttons as well also their story
*fixing color of links and icons in navigation because we introduced a:active in element.scss which overrides them.
> Small fixes for buttons and Icons

- package-lock.json
- package.json
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-navigation-link/ec-navigation-link.vue
Fixed visual glitches in navigation-link and scrolling behaviour in dropdown-search.
> ONL-3932: Fixed visual glitches

- .gitignore
- README.md
- jest.config.js
- package.json
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-modal/ec-modal.spec.js
- src/components/ec-modal/ec-modal.vue
- src/components/ec-popover/ec-popover.spec.js
- src/components/ec-table-footer/ec-table-footer.vue
- src/components/ec-table/__snapshots__/ec-table.spec.js.snap
- src/components/ec-table/ec-table.spec.js
- src/directives/ec-focus-trap/ec-focus-trap.js
- src/directives/ec-focus-trap/ec-focus-trap.spec.js
To verify:
- run `npm run test` and `npm run test:watch` to see the coverage after tests complete
- open coverage folder and check values in generated lcov report.
> ONL-4016: Added test coverage and added missing tests

- .eslintignore
- package-lock.json
- package.json
- src/components/ec-alert/__snapshots__/ec-alert.spec.js.snap
- src/components/ec-alert/ec-alert.vue
- src/components/ec-container/ec-container.story.js
- src/components/ec-container/ec-container.story.scss
- src/components/ec-navigation-link/ec-navigation-link.vue
- src/components/ec-user-info/ec-user-info.vue
- src/scss/components/ec-btn/_ec-btn.scss
Alert component:
- fixed tabindex for close icon, added `:focus`
- to verify, open the story and check the new focus states for close icon when tabbing.
> WIP focus fixes

- src/scss/components/_index.scss
- src/scss/components/ec-card/_ec-card.scss
- src/scss/components/ec-card/ec-card.story.js
Create a card style component.
Create the POC of trade-finance cards.
Design: [link](https://projects.invisionapp.com/share/HPQ2TPOQUM2#/screens/322819731)
Specs:
> Onl 4036 card component

- src/components/ec-donut/__snapshots__/ec-donut.spec.js.snap
- src/components/ec-donut/ec-donut.spec.js
- src/components/ec-donut/ec-donut.story.js
- src/components/ec-donut/ec-donut.vue
- src/components/ec-donut/index.js
- src/main.js
- src/scss/components/ec-card/_ec-card.scss
- src/scss/components/ec-card/ec-card.story.js
- src/scss/tools/_media-queries.scss
In order to test this component, you must check if it has the same behaviour as in the design.
[Invision](https://projects.invisionapp.com/share/HPQ2TPOQUM2#/screens)
> ONL 4037 donut component

- package-lock.json
- package.json
- src/components/ec-toaster/__snapshots__/ec-toaster.spec.js.snap
- src/components/ec-toaster/ec-toaster.vue
To verify:
- open toaster story
- check existing and all new notifications have shadows
> Fixed toaster notifications not having shadows.

- package-lock.json
- package.json
- src/components/ec-user-info/ec-user-info.vue
- src/scss/tools/_typography.scss
> change the line height to 24px

- package-lock.json
- package.json
- src/components/ec-donut/ec-donut.vue
- src/components/ec-table/index.js
- src/main.js
> fix donut component and add index to the table component

- package-lock.json
- package.json
- src/components/ec-table/ec-table.vue
This PR is because the tests are failing on EBO
> fix imports table component

- package-lock.json
- package.json
- src/components/ec-table-head/__snapshots__/ec-table-head.spec.js.snap
- src/components/ec-table-head/ec-table-head.spec.js
- src/components/ec-table-head/ec-table-head.vue
- src/components/ec-table/__snapshots__/ec-table.spec.js.snap
- src/components/ec-table/ec-table.spec.js
- src/components/ec-table/ec-table.story.js
- src/components/ec-table/ec-table.vue
fix table cell, center vertically all the columns and the column who has type icon center the text also
> fix table cell

- .eslintrc.js
- package-lock.json
- package.json
- src/components/ec-container/ec-container.vue
- src/components/ec-panel/__snapshots__/ec-panel.spec.js.snap
- src/components/ec-panel/ec-panel.spec.js
- src/components/ec-panel/ec-panel.story.js
- src/components/ec-panel/ec-panel.vue
- src/components/ec-panel/index.js
- src/components/ec-submenu/ec-submenu.spec.js
- src/components/ec-table/ec-table.spec.js
- src/main.js
- src/scss/settings/_layout.scss
- src/scss/tools/_v-effects.scss
* Ec panel component for chameleon. 
* 2 slots for passing content (header and main)
* 1 close event
* tested on IE11
> ec-panel component

- package-lock.json
- package.json
- src/components/ec-panel/ec-panel.vue
quick-fix that adds to chameleon a container class for the panel.
> ec-panel-container class

- package-lock.json
- package.json
- src/components/ec-dropdown-search/__snapshots__/ec-dropdown-search.spec.js.snap
- src/components/ec-dropdown-search/ec-dropdown-search.spec.js
- src/components/ec-dropdown-search/ec-dropdown-search.story.js
- src/components/ec-dropdown-search/ec-dropdown-search.vue
Changed the way how maxHeight for the dropdown is calculated (moved from CSS to popper logic)
> Added an option to specify a template for dropdown-search item

- package-lock.json
- package.json
- src/components/ec-input-field/ec-input-field.story.js
- src/components/ec-input-field/ec-input-field.vue
Add the background for the disabled state that I need on the form of the deposit section
> Add custom background to the disabled state

- package-lock.json
- package.json
- src/components/ec-checkbox/__snapshots__/ec-checkbox.spec.js.snap
- src/components/ec-checkbox/ec-checkbox.spec.js
- src/components/ec-checkbox/ec-checkbox.story.js
- src/components/ec-checkbox/ec-checkbox.vue
- src/components/ec-checkbox/index.js
- src/components/ec-input-field/ec-input-field.story.js
- src/components/ec-input-field/ec-input-field.vue
- src/main.js
- src/scss/tools/_accessibility.scss
- src/scss/tools/_borders.scss
- src/scss/tools/_index.scss
- src/scss/tools/_typography.scss
Checkbox component with ec-icon instead of css pseudo-elements
> EcCheckbox with ec-icon

- package-lock.json
- package.json
- src/components/ec-dropdown-search/__snapshots__/ec-dropdown-search.spec.js.snap
- src/components/ec-dropdown-search/ec-dropdown-search.spec.js
- src/components/ec-dropdown-search/ec-dropdown-search.story.js
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-dropdown/__snapshots__/ec-dropdown.spec.js.snap
- src/components/ec-dropdown/ec-dropdown.spec.js
- src/components/ec-dropdown/ec-dropdown.story.js
- src/components/ec-dropdown/ec-dropdown.vue
Add the loading state to the dropdown and dropdown-search.
I discussed with @matallo that is mandatory if is loading we cannot display the 'no results found' field
> ONL-4193 Dropdown loading state

- package-lock.json
- package.json
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-dropdown/ec-dropdown.story.js
- src/scss/tools/_ec-dropdown.scss
Change requested by @victoriaportillo in UAT.
> ONL-4122: fix: Fixed hover state for dropdown CTA.

- package-lock.json
- package.json
- src/scss/components/ec-card/_ec-card.scss
- src/scss/components/ec-card/ec-card.story.js
> ONL-4217: feat: Add interactive cards

- package-lock.json
- package.json
- src/components/ec-dropdown/__snapshots__/ec-dropdown.spec.js.snap
- src/components/ec-dropdown/ec-dropdown.spec.js
- src/components/ec-dropdown/ec-dropdown.vue
This PR is needed to add events to when we open a dropdown, for example when we need to add some HUHA event or interaction.
Its only about to add the open emit to the dropdown component
> ONL-4284 add open event to the dropdown

- src/components/ec-modal/__snapshots__/ec-modal.spec.js.snap
- src/components/ec-modal/ec-modal.spec.js
- src/components/ec-modal/ec-modal.story.js
- src/components/ec-modal/ec-modal.vue
In this PR I add the prop z-index to the modal component to solve the ONL-4069 issue.
Check the comments on the code to see if all agree on have the z-index prop fixed between 200-250.
> ONL-4069 add z-index to the modal component

- package-lock.json
- package.json
- src/components/ec-currency-input/__snapshots__/ec-currency-input.spec.js.snap
- src/components/ec-currency-input/ec-currency-input.spec.js
- src/components/ec-currency-input/ec-currency-input.story.js
- src/components/ec-currency-input/ec-currency-input.vue
…down currencies
This PR is to add the disabled to the currency dropdown and the disabled amount input on the currency input.
> Onl 4168 add disabled state currency dropdown

- package-lock.json
- package.json
- src/components/ec-amount-input/ec-amount-input.vue
- src/components/ec-currency-input/ec-currency-input.spec.js
It is now official: I, personally, from the bottom of my heart, hate this component. :)
> ONL-4443: fix: Fixing currency input again

- src/components/ec-main-container/__snapshots__/ec-main-container.spec.js.snap
- src/components/ec-main-container/ec-main-container.vue
Sub task: https://fxsolutions.atlassian.net/browse/ONL-4576
- Migrating the ec-main-component to use Tailwind utility classes
- added data-test attribute
> ONL-4576 - Using tw classes in main container component

- package-lock.json
- package.json
- postcss.config.js
- src/components/ec-main-container/__snapshots__/ec-main-container.spec.js.snap
- src/components/ec-main-container/ec-main-container.story.js
- src/components/ec-main-container/ec-main-container.vue
> main container fix css

- package-lock.json
- package.json
- src/components/ec-main-container/__snapshots__/ec-main-container.spec.js.snap
- src/components/ec-main-container/ec-main-container.spec.js
- src/components/ec-main-container/ec-main-container.vue
- src/components/ec-submenu/__snapshots__/ec-submenu.spec.js.snap
- src/components/ec-submenu/ec-submenu.spec.js
- src/components/ec-submenu/ec-submenu.story.js
- src/components/ec-submenu/ec-submenu.vue
Small fixed required for new TF Gov schemes:
1. ec-main-container without intro have a huge bottom margin
2. fixed submenu not being tabbable (a11y). 
3. fixed submenu jumping on small screens when changing the tab.
> Onl 4683 visual fixes

- package-lock.json
- package.json
- src/components/ec-popover/ec-popover.story.js
- src/components/ec-popover/ec-popover.vue
- src/scss/components/_v-tooltip.scss
- src/styles/components/index.css
- src/styles/components/v-tooltip.css
- src/styles/tools/ec-z-level-all.css
- src/styles/tools/index.css
https://fxsolutions.atlassian.net/browse/ONL-4673
> ONL-4673 ec-popover migration

- package-lock.json
- package.json
- src/components/ec-inline-input-field/index.js
- src/main.js
Export `EcInlineInputField` component via main.js
> feat(ONL-4842): Export EcInlineInputField component via main.js

- package-lock.json
- package.json
- src/components/ec-currency-input/__snapshots__/ec-currency-input.spec.js.snap
- src/components/ec-currency-input/ec-currency-input.spec.js
- src/components/ec-currency-input/ec-currency-input.story.js
- src/components/ec-currency-input/ec-currency-input.vue
Adding the capability of defining a currency selector placeholder in the Currency Input component
> feat(ONL-4980): Currency selector placeholder in the Currency Input component

- package-lock.json
- package.json
- src/components/ec-btn-dropdown/__snapshots__/ec-btn-dropdown.spec.js.snap
- src/components/ec-btn-dropdown/ec-btn-dropdown.spec.js
- src/components/ec-btn-dropdown/ec-btn-dropdown.vue
Add extra prop "list-data-test" at the btn dropdown
> ONL-5808:feat:add prop list-data-test at the btn-dropdown

- package-lock.json
- package.json
- src/components/ec-dropdown/__snapshots__/ec-dropdown.spec.js.snap
- src/components/ec-dropdown/ec-dropdown.spec.js
- src/components/ec-dropdown/ec-dropdown.story.js
- src/components/ec-dropdown/ec-dropdown.vue
We have the requirement to add a tooltip to the label of the Dropdown. This feature was already available in the EcInputField component.
I just added a prop to surface the existing one.
> ONL-4171: Tooltip in the dropdown label

- package-lock.json
- package.json
- src/components/ec-input-field/__snapshots__/ec-input-field.spec.js.snap
- src/components/ec-input-field/ec-input-field.spec.js
- src/components/ec-input-field/ec-input-field.story.js
- src/components/ec-input-field/ec-input-field.vue
Bottom note for input-field using the same approach as in currency-input.
> ONL-6085: feat: Added warning bottom note to input field.

- package-lock.json
- package.json
- src/components/ec-modal/ec-modal.vue
> ONL-5831:fix:modal hide overflow x

- src/styles/generic/fonts.css
Checkout the docs: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display
Updated Roboto v20 -> 29 and Roboto Condensed v18 -> 19
> ONL-6153: feat: Added font-display: swap for all fonts.

- src/components/ec-phone-number-input/__snapshots__/ec-phone-number-input.spec.js.snap
- src/components/ec-phone-number-input/ec-phone-number-input.spec.js
- src/components/ec-phone-number-input/ec-phone-number-input.vue
This PR removes alphabetical sorting for countries for phone number input. This will done on EBO side.
> ONL-6298 - Remove alphabetical sorting for phone number component

- package-lock.json
- package.json
- src/components/ec-btn-dropdown/ec-btn-dropdown.vue
Increased the max-width of the dropdown button to allow for German text: 'Konvertieren & bezahlen' to not add ellipsis
> [ONL-6602] Increased max-width of dropdown button

- src/components/ec-button-group/ec-button-group.vue
Migrated the Btn Group to Vue 3
> ONL-6723 Migrated btn group to Vue 3

- src/components/ec-container/ec-container.spec.js
- src/components/ec-container/ec-container.vue
- src/components/ec-main-container/ec-main-container.spec.js
- src/components/ec-main-container/ec-main-container.vue
Migrate container and main container
> [ONL 6697] Migrate container and main container

- package-lock.json
- package.json
- src/components/ec-main-container/__snapshots__/ec-main-container.spec.js.snap
- src/components/ec-main-container/ec-main-container.vue
> [ONL- 6826] main container cta button adjustments

- src/components/ec-submenu/ec-submenu.vue
> [ONL-6713] - Chore - Migrate submenu to vue3

- package-lock.json
- package.json
- src/components/ec-timer/ec-timer.vue
migrated time componet to vue3 
Paired with @derrick-g
> [ONL-6712] - migrate ec-timer to vue3

- package-lock.json
- package.json
- src/components/ec-privacy-policy/ec-privacy-policy.vue
> [ONL-6714] - Migrate privacy policy component

- src/components/ec-inline-actions/ec-inline-actions.vue
> [ONL-6719] chore - Migrate inline actions

- package-lock.json
- package.json
- src/components/ec-full-screen-overlay/ec-full-screen-overlay.spec.js
- src/components/ec-full-screen-overlay/ec-full-screen-overlay.vue
- src/components/ec-popover/__snapshots__/ec-popover.spec.js.snap
- src/components/ec-popover/ec-popover-provide.js
- src/components/ec-popover/ec-popover.spec.js
- src/components/ec-popover/ec-popover.vue
- src/main.js
This adds provide functionality to change the container for where the popover will be placed within, default is BODY if none stated, otherwise it will use the ref container provided.
> ONL-7032 Adds popover inject functionality

- CODEOWNERS
> [ONL-7084] chore: add Anton as codeowner

- package-lock.json
- package.json
- src/components/ec-input-field/index.ts
- src/components/ec-phone-number-input/ec-phone-number-input.vue
- src/components/ec-phone-number-input/index.js
- src/main.js
For the proper typing support using Chameleon components in EBO, we should provide .d.ts file for that
> ONL-6959 Add types definition

- package-lock.json
- package.json
- src/components/ec-input-field/__snapshots__/ec-input-field.spec.ts.snap
- src/components/ec-input-field/ec-input-field.spec.ts
- src/components/ec-input-field/ec-input-field.story.ts
- src/components/ec-input-field/ec-input-field.vue
- src/components/ec-input-field/types.ts
Exposes the iconType attribute to inputField allowing us to decide on the colour of the icon used.
> ONL-7169 Adds iconType to inputField

- package-lock.json
- package.json
- src/components/ec-metroline/components/ec-metroline-item/ec-metroline-item.vue
- Metroline item content: Stopped flexbox item from overflowing
> [ONL-7180]-Summary container maximum width

- src/components/ec-option-card/__snapshots__/ec-option-card.spec.ts.snap
- src/components/ec-option-card/ec-option-card.vue
Amendment of ec-option-card component with data test for title
> ONL-7395: Added data test attribute to title of ec-option-card

- package.json
- src/components/ec-option-card/__snapshots__/ec-option-card.spec.ts.snap
- src/components/ec-option-card/ec-option-card.spec.ts
- src/components/ec-option-card/ec-option-card.vue
New data tests are set based on disabled and type flag
> ONL-7401: Added data-test for different states of ec-option-card

- package-lock.json
- package.json
> [ONL-7467] - update chameleon version 

- src/components/ec-tag/index.ts
- src/main.js
> [ONL-7763] chore:export tag types

- .github/dependabot.yml
- CODEOWNERS
Updating Codeowners.
Adding Raul and Alan :) 
End of an era though as I am removing Milos.
Thank you @mcibique for all your knowledge. 
We are standing in the shoulders/contributions of a "giant".
> [CHUX-308] Update codeowners

- .github/dependabot.yml
- CODEOWNERS
This PR is for removing Derrick.
Thank you @derrick-g for your contributions, was amazing having you in the team!
> [CHUX-458] Chore remove-derrick

- package-lock.json
- package.json
- src/components/ec-modal/ec-modal.spec.ts
- src/components/ec-modal/ec-modal.vue
Moved focusTrapTarget from ec-modal__content to ec-modal
> [CHUX-658] Fix: 2FA dropdown

- package-lock.json
- package.json
- src/components/ec-menu/ec-menu.vue
- src/components/ec-menu/types.ts
- src/components/ec-navigation-link/ec-navigation-link.vue
- src/components/ec-navigation/__snapshots__/ec-navigation.spec.ts.snap
- src/components/ec-navigation/ec-navigation.vue
More tweaks for chameleon navigation in order to support correctly the light mode
> [CHUX-467] futher tweaks in chameleon navigation
