- package-lock.json
- package.json
- src/scss/components/_v-tooltip.scss
latest version of sass spec requires the calc() arguments to be interpolated.
EBO uses `sass@1.23.3` which require all variables in `calc()` being interpolated. see https://sass-lang.com/documentation/syntax/special-functions#calc-element-progid-and-expression.
I have updated `sass` package here and fixed all occurrences.
> Sass fixes

- README.md
- package-lock.json
- package.json
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-navigation/ec-navigation.vue
To verify dropdown search:
1. Open any dropdown search story
2. Click the dropdown search element
3. The search input should not have any outline when gaining the focus.
To verify navigation width:
1. Open container with navigation story
2. Check the width of the navigation is 280px when isCollapsable knob is false
3. Check the width of the navigation is 256px when isCollapsable knob is true
4. Verify the navigation can be collapsed.
> Remove outline from search input in dropdown search and fix the width of the navigation

- package-lock.json
- package.json
- src/components/ec-user-info/ec-user-info.vue
- src/scss/components/ec-btn/_ec-btn.scss
Last set of fixes (I hope):
To verify the button:
1. go to story for button > basic
2. choose primary-reserve type and disabled
3. check the visual style
To verify user info:
1. go to user info > basic story
2. in the knobs, set the name of the user to empty string
3. in the knobs, make the user info collapsable
4. verify the client selector dropdown is centered vertically
> ONL-3932: Fixed bugs found during the UAT.

- package-lock.json
- package.json
- src/components/ec-user-info/ec-user-info.vue
- src/scss/components/ec-btn/_ec-btn.scss
- src/scss/components/ec-btn/ec-btn.story.js
To test this PR you need to go to the button component and test a new status here is the list of that:
- Primary-reverse with Outline.
- Secondary-reverse
- Secondary-reverse with Outline
- Success-reverse
- Success-reverse with Outline
- Error-reverse
- Error-reverse with Outline
- Warning
- Warning-reverse
- Warning-reverse with Outline
The Frontify needs to be updating to compare with that, I just ask for that change.
Here is the image with all the buttons, you can check it with the [here](https://chameleon-git-onl-3966-reverse-buttons.ebury.now.sh/?path=/story/button--all-buttons-dark)
> ONL-3966 Reverse status and warning status

- package-lock.json
- package.json
- src/components/ec-container/ec-container.story.js
- src/components/ec-navigation-link/ec-navigation-link.vue
* Added :focus style for active navigation-link.
* Added active state example to the container story for better visibility.
Currently, the :focus style changes the color of the item to blue, so the text is not visible. We need to keep the white `color` of the text but change the `background-color`.
To verify:
- Open Storybook > Layout > Container > with navigation story
- Check the active navigation item focus using Tab key
- The text should stay white, the background-color should change.
> Focus style for active navigation-link

- .eslintrc.js
- .npmignore
- .storybook/webpack.config.js
- package-lock.json
- package.json
- src/components/ec-container/ec-container.story.js
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-toaster/ec-toaster-touch.js
- src/directives/ec-focus-trap/ec-focus-trap.js
This is preparation for moving EBO code to new folder. We can reuse eslintrc.js and stylelintrc.js in EBO, because of the extend functionality of eslint and stylelint, e.g.
```
// eslintrc.js in EBO
module.exports = {
extends: [ '@ebury/chameleon-components/.eslintrc.js' ]
}
```
Once we have the monorepo, we can move these rc files into separate packages, publish them and extend EBO and chameleon-components from it.
To verify:
- check the eslintrc.js and stylelintrc.js files are in published package.
- verify there are no errors when running lint task
> Expose eslintrc in the package

- package.json
Recently, we added script into package.json to automate the publish process from local machine:
```
"prepublish": "npm run lint && npm run test",
"publish": "npm version patch && npm publish && git push --follow-tags"
```
Problem: the name `publish` is actually reserved alias, and running `npm publish` inside 'publish' script will re-run the command in infinite loop, publishing the package multiple times.
Check the documentation for publish in https://docs.npmjs.com/misc/scripts#description:
> publish, postpublish: Run AFTER the package is published.
Two solutions here:
1. change commands to this:
```
"prepublish": "npm run lint && npm run test && npm version patch",
"publish": "git push --follow-tags"
```
2. rename the commands to:
```
"prerelease": "npm run lint && npm run test", …
```
> fix: Renamed publish and prepublish scripts to relase and prerelease.

- src/scss/elements/_elements.scss
- src/scss/generic/_index.scss
- src/scss/generic/_normalize.scss
Added normalize.css and cherry picked rules we need. This will fix a problem with `main` element not having paddings/margins on IE11.
I have cherry-picked only things we need. The only potential problem would be with this:
```
button,
input,
optgroup,
select,
textarea {
font-family: inherit; /* 1 */
font-size: 100%; /* 1 */
line-height: 1.15; /* 1 */
margin: 0; /* 2 */
}
```
... because we already have the button implemented. I have verified that the `ec-btn` overrides all four properties so it will not be a problem.
> Added normalize.css and cherry picked rules we need.

- package-lock.json
- package.json
- src/components/ec-modal/ec-modal.spec.js
- src/components/ec-modal/ec-modal.vue
- src/directives/ec-focus-trap/ec-focus-trap.js
- src/directives/ec-focus-trap/ec-focus-trap.spec.js
* focus-trap should trapping the focus inside the modal and not on backdrop.
* fixed modal not unregistering keyup events properly.
* fixed focus-trap not deactivating itself after modal being destroyed.
> Fixed ec-modal and ec-focus-trap.

- package-lock.json
- package.json
- src/components/ec-modal/__snapshots__/ec-modal.spec.js.snap
- src/components/ec-modal/ec-modal.spec.js
- src/components/ec-modal/ec-modal.vue
This pr is to fix an error on the ec-modal. 
When we click on the close button a "close" event is fired but we don't pass the value. The ec-modal was working because the value was undefined which is falsy. Now I set it specifically to false. Also added tests for v-model.
> quickfix-ec-modal

- package-lock.json
- package.json
- src/components/ec-input-field/ec-input-field.vue
Update the border color for the text input fields. 
Dropdown search and dropdown are already correct.
> quickfix:update border color for ec-input

- src/components/ec-dropdown-search/__snapshots__/ec-dropdown-search.spec.js.snap
- src/components/ec-dropdown-search/ec-dropdown-search.spec.js
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-dropdown/__snapshots__/ec-dropdown.spec.js.snap
- src/components/ec-dropdown/ec-dropdown.spec.js
- src/components/ec-dropdown/ec-dropdown.vue
Pairing with @jaimeperezpedra on this.
While working on add supplier modal discovered that ec-dropdown not showing on modal.
We need to pass the level as a prop to the ec-dropdown--> ec-dropdowns-search--> ec-popover
Thoughts about this solution?
> Passing z-index to from ec-dropdown to ec-popover

- package-lock.json
- package.json
- src/components/ec-container/ec-container.vue
... when the content is too big (e.g. table with many columns)
Every `flex: 1` should have `min-width: 0` because then the element respects the width of the parent and not the width of its children.
How to verify: 
1. go to trade finance view
2. switch the mobile view (e.g. Galaxy S5)
3. the content of the container is >500px because of the submitted requests table (it should be less than 360px). -> bug
4. apply the fix from this PR. -> should be back to normal and the table should be scrollable.
> fix: Fixed ec-container stretches beyond 100% width 

- package-lock.json
- package.json
- src/components/ec-modal/ec-modal.story.js
- src/components/ec-modal/ec-modal.vue
Fix refs on the buttons of the modal because was throwing an error o the focus trap.
This was the error:
> fix refs on the buttons of the modal 

- package-lock.json
- package.json
- src/components/ec-dropdown-search/__snapshots__/ec-dropdown-search.spec.js.snap
- src/components/ec-dropdown-search/ec-dropdown-search.spec.js
- src/components/ec-dropdown-search/ec-dropdown-search.story.js
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-dropdown/__snapshots__/ec-dropdown.spec.js.snap
- src/components/ec-dropdown/ec-dropdown.spec.js
- src/components/ec-dropdown/ec-dropdown.story.js
- src/components/ec-dropdown/ec-dropdown.vue
Because of suppliers-dropdown has custom item template with custom text colors, we need to handle the case that the item is selected in the item template. Unfortunately, the information if item is selected is buried in ec-dropdown-search so this PR exposes it to public.
> ONL-4269 Pass information that dropdown item is selected to custom slot.

- package-lock.json
- package.json
- src/components/ec-loading/ec-loading.vue
- src/scss/settings/_z-index.scss
On some cases the loading spinner is not visible. In order to work properly we need to add z-index to ensure that will be on top of every other element (except notifications).
> Quickfix ec-loading z-index

- package-lock.json
- package.json
- src/scss/components/_index.scss
- src/scss/components/ec-action-list/_ec-action-list-group.scss
- src/scss/components/ec-action-list/_ec-action-list-item.scss
- src/scss/components/ec-action-list/_ec-action-list.scss
- src/scss/components/ec-action-list/ec-action-list.story.js
- src/scss/tools/_borders.scss
This will be used to build the Download statements panel in the new stack. I decided to add it as a scss component because we will use it also to build the available actions inside the account details panel.
**Download Staments**
**Account Panel**
> feat(4293) add action-list scss component

- package-lock.json
- package.json
- src/components/ec-panel/__snapshots__/ec-panel.spec.js.snap
- src/components/ec-panel/ec-panel.spec.js
- src/components/ec-panel/ec-panel.story.js
- src/components/ec-panel/ec-panel.vue
- This story is for adding to the EcPanel the possibility of displaying (is optional) a new button in the top-left corner, with a left arrow icon.
- This button just will emit an event to point out that user wants to go back to a previous panel.
- To display it in Storybook, go to Panel basic component, and mark "With the back button visible" in the Knobs tab.
> feat(ONL-4295): Adding back button to EcPanel

- src/components/ec-amount-input/ec-amount-input.spec.js
- src/components/ec-amount-input/ec-amount-input.story.js
- src/components/ec-amount-input/ec-amount-input.vue
- src/directives/ec-amount/utils.js
- src/directives/ec-amount/utils.spec.js
Two things have been fixed:
1. Amount input now properly handles currencies without decimals and doesn't allow typing decimal separator.
2. Negative sign in amount input was causing weird behaviours, e.g. you could type `-` in the middle of a number; or you have to press `-` twice in empty input to get at least one `-` in the input.
> ONL-4270: currencies without decimals

- package-lock.json
- package.json
- src/components/ec-smart-table/__snapshots__/ec-smart-table.spec.js.snap
- src/components/ec-table-footer/ec-table-footer.vue
- src/components/ec-table-head/__snapshots__/ec-table-head.spec.js.snap
- src/components/ec-table-head/ec-table-head.spec.js
- src/components/ec-table-head/ec-table-head.vue
- src/components/ec-table-sort/__snapshots__/ec-table-sort.spec.js.snap
- src/components/ec-table-sort/ec-table-sort.vue
- src/components/ec-table/__snapshots__/ec-table.spec.js.snap
- src/components/ec-table/ec-table.spec.js
- src/components/ec-table/ec-table.story.js
- src/components/ec-table/ec-table.vue
- src/scss/elements/_tables.scss
- src/scss/tools/_scrollbars.scss
- src/scss/tools/_typography.scss
In this ticket we add these features:
- New event when you click to the row called 'row-click'.
- Vertical and Horizontal scroll bar when you set the height of the table or when you set the max-width of some columns and the table cannot cover all the columns with space.
- New info icon with a tooltip on the header.
- The possibility to make sticky the first or the last column of the table.
- Change the style of the table on the header capitalize and the paddings also the paddings of the cells and between the title.
- Overwrite the defaults styles of the scroll-bars.
Working with Maroua
> ONL-4376 add the new features to the table component

- package-lock.json
- package.json
- src/components/ec-smart-table/__snapshots__/ec-smart-table.spec.js.snap
- src/components/ec-table-head/__snapshots__/ec-table-head.spec.js.snap
- src/components/ec-table-head/ec-table-head.spec.js
- src/components/ec-table-head/ec-table-head.vue
- src/components/ec-table/__snapshots__/ec-table.spec.js.snap
- src/components/ec-table/ec-table.spec.js
- src/components/ec-table/ec-table.story.js
- src/components/ec-table/ec-table.vue
I would like to add a couple of new features to the _EcTable_ component.
- To be able to align columns to the right (by default they are all aligned to the left, except the ones containing an icon that are centered).
- To be able to define a _maxWidth_ of column. If the text inside the cell requires more space than the column offers, use the _ellipsis_.
> Onl 4002 align to the right and max width

- package-lock.json
- package.json
- src/components/ec-currency-input/__snapshots__/ec-currency-input.spec.js.snap
- src/components/ec-currency-input/ec-currency-input.spec.js
- src/components/ec-currency-input/ec-currency-input.story.js
- src/components/ec-currency-input/ec-currency-input.vue
- src/components/ec-dropdown/__snapshots__/ec-dropdown.spec.js.snap
- src/components/ec-input-field/__snapshots__/ec-input-field.spec.js.snap
- src/components/ec-input-field/ec-input-field.spec.js
- src/components/ec-input-field/ec-input-field.vue
The design:
Little bit of details why I have split the disabled state of dropdown and created a new `<div>` instead of using `disabled` prop of `ec-dropdown` as it was before:
Disabled ec-dropdown renders:
```
<input disabled value="EUR">
```
When I disable a dropdown inside ec-currency-input, I need the the dropdown to fit the width of its content. That's not possible when the content is inside an `input`. input has width of `201px` and ignores attempts like `min-width: 0; flex-grow: 0; width: auto;`. That's why in this component I have switched the disabled state to be 
```
<div>EUR</div>
```
Second problem which is solved by using a `div` is that Uve insists on having different background color for disabled currencies than we use in regular dropdown and input-field components. I …
> ONL-4168: feat: Reworked how currency input displays disabled currencies

- src/styles/utilities/typography.story.js
- tailwind.config.js
A quick fix:
After merging all 4 ITCSS layers to master I decided to run visual regression tests using old SASS and new PostCSS/Tailwind and tests detected discrepancies. Those were caused by typography plugin I wrote in tailwind:
```
h6: {
fontSize: '14px', lineHeight: '24px', fontWeight: 500, '@apply uppercase': '',
},
```
works only in generated utility class:
```
.tw-h6 {
...
text-transform: uppercase;
}
```
but it doesn't work in `@apply`:
```
h6 {
@apply tw-h6;
}
/* outputs invalid CSS: */
h6 {
...
@apply uppercase:
}
```
It seems like tailwind cannot handle nested apply calls.
I have fixed it and run the regression tests again, everything seems working fine now.
> ONL-4419: fix: typography plugin produces invalid CSS.

- README.md
- package-lock.json
- package.json
- src/components/ec-amount-input/ec-amount-input.spec.js
- src/components/ec-amount-input/ec-amount-input.story.js
- src/components/ec-amount-input/ec-amount-input.vue
- src/components/ec-currency-input/ec-currency-input.story.js
- src/utils/number-format.js
- src/utils/number-format.spec.js
Amount input uses Intl API for detecting decimal and grouping separator:
```
function getSeparator(locale, type) {
return new Intl.NumberFormat(locale)
.formatToParts(1111.1)
.find(part => part.type === type)
.value;
}
getSeparator('en', 'decimal') // '.'
getSeparator('en', 'group') // ','
```
But the problem is that `formatToParts` doesn't exist on IE11. There is a polyfill but not for NumberFormat. So I wrote our own detection and validated it against all locales in the world that are shipped with `intl` package.
I found strange behaviour of my functions for Swedish locale, where `getGroupingSeparator` returns ',' instead of empty space ` `. I run the same test with `formatToParts` function and I got the same bug. This is happening only on Chromium browsers, while Firefox and IE11! got …
> ONL-4443: fix: Fixed the way how decimal separator and group separator are detected

- package-lock.json
- package.json
- src/components/ec-amount-input/ec-amount-input.vue
- src/components/ec-currency-input/ec-currency-input.spec.js
Days without a fix of currency-input: 0
This issue was found while testing latest IE11 fixes in this component.
Problem, if grouping separator is the same as the decimal separator for JS, then changing a currency leads to weird behaviour:
1. go to https://chameleon.ebury.now.sh/?path=/story/currency-input--basic
2. Chose es locale in knobs
3. Select GBP
4. Insert 123.456,78
5. Change currency to EUR
6. The value in amount should stay 123.456,78 but it changes to 12.345.678!
This was caused by the fact that grouping separator in `es` locale is `.`, same as decimal separator in JS. The problem doesn't happen with `en` locale because their grouping separator is `,`. 
All fixed!
> ONL-4443: fix: Fixed currency input weird behaviour when changing currency

- package-lock.json
- package.json
- tailwind.config.js
Remove warning which appears during production build:
```
⚠️  Tailwind is not purging unused styles because no template paths have been provided.
If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
removing unused styles, set `purge: false` in your Tailwind config file to silence
this warning.
```
> chore: Fix warning coming from tailwind when building the production app

- package-lock.json
- package.json
- src/components/ec-smart-table/__snapshots__/ec-smart-table.spec.js.snap
- src/components/ec-smart-table/ec-smart-table.story.js
- src/components/ec-table-head/ec-table-head.spec.js
- src/components/ec-table-head/ec-table-head.vue
- src/components/ec-table/ec-table.spec.js
- src/enums/sort-direction-cycle.js
- src/hocs/ec-with-sorting/__snapshots__/ec-with-sorting.spec.js.snap
- src/hocs/ec-with-sorting/ec-with-sorting.js
- src/hocs/ec-with-sorting/ec-with-sorting.spec.js
**TL,DR;**
- Adds `defaultSortCycle` property to `EcWithSorting`. This property controls the default sort cycle of all the columns, if none is applied to specific column. It is an array like: `[null, 'asc','desc']` (default)
- Column object definition can override the default for any specific column, providing a `sortCycle` property
This PR adds the possibility to configure the cycle in which the sorts are applied to the table when a user clicks on the table column. To represent this cycle, I am using an array. The first element of the array represents the state where no sort is applied, and the elements 1 and 2 represents the states after the user clicks. For instance, the current sorting cycle goes like this: 'none', 'ascending', 'descending'. It will be represented as `[null, 'asc', …
> ONL-4585 feat: Allow the sorting order of a column to be configurable

- package-lock.json
- package.json
- src/components/ec-btn/__snapshots__/ec-btn.spec.js.snap
- src/components/ec-btn/ec-btn.spec.js
- src/components/ec-btn/ec-btn.vue
Bugs fixed:
1. Couldn't pass route object to the `to` property of ec-btn, e.g.
```
<ec-btn to="/dashboard">This is okay</ec-btn>
<ec-btn :to="{ name: 'dashboard' }">This is not</ec-btn>
```
2. When passing down props to `<router-link>`, we were always passing `href` as null causing the router-link generates an anchor without the href.
> ONL-4311: fix: Fixed ec-btn as router-link behaviour.

- .storybook/webpack.config.js
- jest.config.js
- package-lock.json
- package.json
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-inline-actions/ec-inline-actions.spec.js
- src/components/ec-navigation-link/ec-navigation-link.spec.js
- src/components/ec-popover/ec-popover.spec.js
- src/components/ec-table/ec-table.story.js
- src/components/ec-user-info/ec-user-info.spec.js
- src/styles/components/ec-btn/ec-btn.story.js
After installing the 1.0.5 in EBO, webpack started throwing errors that `@/enums/key-code` doesn't exist. It's because we should not be using webpack aliases in this library because `@/` alias can change the value in the application.
We could use them in stories and spec.js but then we cannot spot problem that the alias is being used in the "production" code (vue and js files). I decided to remove them completely from storybook and jest. We were using it only on a few places and most of the usage didn't make sense anyway.
> fix: Removed webpack aliases

- src/components/ec-dropdown-search/ec-dropdown-search.keyboard-navigation.spec.js
- src/components/ec-dropdown-search/ec-dropdown-search.spec.js
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-dropdown/ec-dropdown.story.js
- src/components/ec-modal/ec-modal.spec.js
The keyboard navigation on the CTA and Search area will work with the tab key, and the items will work as it was from before nothing changes with the arrows keys
> ONL-4183 Add keyboard navigation for dropdown search component - CTA and Search areas

- package-lock.json
- package.json
- src/components/ec-smart-table/__snapshots__/ec-smart-table.spec.js.snap
- src/components/ec-smart-table/ec-smart-table.spec.js
- src/components/ec-smart-table/ec-smart-table.story.js
- src/components/ec-smart-table/ec-smart-table.vue
- src/components/ec-table-footer/__snapshots__/ec-table-footer.spec.js.snap
- src/components/ec-table-footer/ec-table-footer.vue
- src/components/ec-table-pagination/__snapshots__/ec-table-pagination.spec.js.snap
- src/components/ec-table-pagination/ec-table-pagination.spec.js
- src/components/ec-table-pagination/ec-table-pagination.vue
- src/components/ec-table-pagination/index.js
- src/components/ec-table/__snapshots__/ec-table.spec.js.snap
- src/enums/pagination.js
- src/hocs/ec-with-pagination/__snapshots__/ec-with-pagination.spec.js.snap
- src/hocs/ec-with-pagination/ec-with-pagination.js
- src/hocs/ec-with-pagination/ec-with-pagination.spec.js
- src/hocs/ec-with-pagination/index.js
- src/hocs/ec-with-sorting/ec-with-sorting.js
- src/main.js
- src/styles/components/v-tooltip.css
EcSmartTable has a new prop: `isPaginationEnabled`, set to false by default. Currently balances table in EBO doesn't need pagination so I made it optional. 
I didn't create a story for ec-table-pagination because it doesn't make sense to reuse this component anywhere else outside of the table (just like we don't have ec-table-head, ec-table-footer, etc.)
The biggest development issue is that we would have to provide a translations for current page string for every table we use in EBO. The text says `1 of 10 pages (67 payments)`. So every table will require its own translation. The default value is:
```
<slot
name="pages"
v-bind="{ page, numberOfItems, totalPages, total }"
>
<span>{{ page }}&nbsp;of&nbsp;{{ totalPages }} pages</span>
<span>({{ total }}&nbsp;items)</span>
</slot>
```
^^ …
> ONL-4900: feat: Added pagination

- package-lock.json
- package.json
- src/components/ec-smart-table/__snapshots__/ec-smart-table.spec.js.snap
- src/components/ec-smart-table/ec-smart-table.spec.js
- src/components/ec-smart-table/ec-smart-table.vue
Problem we discovered in ONL-4901 PR in EBO. ec-smart-table can cause an infinite loop when we touch the data object of its parent while doing the fetching.
```
dataSource: {
fetch: async ({ page, numberOfItems }, cancelToken) => {
const response = await getFees(page, numberOfItems, cancelToken);
const { summary } = response;
const { totalAmount, currency } = summary;
this.footerData = { currency, totalAmount: totalAmount }; // this line forces the fees view to re-rendered and the chain of events will cause an infinite loop
})
}
```
The component uses the ec-smart-table this way:
```
<ec-smart-table>
<template #footer>
<ebo-fees-and-charges-table-footer
:currency="footerData.currency"
:amount="footerData.totalAmount"
/>
</template>
</ec-smart-table>
```
If you assign anything to …
> ONL-4901: fix: Fixed ec-smart-table can cause infinite loop if data of the parent component have been modified in the fetch phase

- package-lock.json
- package.json
- src/hocs/ec-with-abortable-fetch/__snapshots__/ec-with-abortable-fetch.spec.js.snap
- src/hocs/ec-with-abortable-fetch/ec-with-abortable-fetch.js
- src/hocs/ec-with-abortable-fetch/ec-with-abortable-fetch.spec.js
We need to reset the fetchError in the state of the component when the fetch method is called.  Currently, if a request fails, the subsequent requests are considered to fail because the state is not reset. This is an issue now that we are implementing the filters and there can be more requests if the user selects a new filter
>  [ONL-5378] EcWithAbortableFetch: fetchError in the state is not reset

- package-lock.json
- package.json
- src/components/ec-smart-table/ec-smart-table.vue
Based on our compatibility matrix on EBO, we allow firefox 44 but if we do login in EBO and we go to the Dashboard, we cannot see it because there is the next exception:
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function. _webpack_require_()
app.js:876
hotCreateRequire/fn()
app.js:168
<anonymous>
index.js:2
["./node_modules/@ebury/chameleon-components/src/components/ec-smart-table/index.js"]()....
> ONL-5407:fix: Fix declared function

- package-lock.json
- package.json
- src/components/ec-btn-dropdown/ec-btn-dropdown.vue
In this PR I increase the max number of visible items for the button dropdown to Infinity. 
The default visible items for the dropdown search is 4. For btn dropdown though we don't want the scrollbar at all even if we have a large number of items. For this reason should be set to infinity.
> ONL-5897:feat:infinite visible items for btn dropdown

- package-lock.json
- package.json
- src/components/ec-currency-input/__snapshots__/ec-currency-input.spec.js.snap
- src/components/ec-dropdown-search/__snapshots__/ec-dropdown-search.spec.js.snap
- src/components/ec-dropdown-search/ec-dropdown-search.spec.js
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-dropdown/__snapshots__/ec-dropdown.spec.js.snap
- src/components/ec-dropdown/ec-dropdown.spec.js
Selecting an item from a dropdown in tests is problematic when there are multiple dropdowns on the page. The dropdown uses ec-popover for displaying the dropdown list of items but these popovers stay in the document body for a couple of seconds after closed. This causes problems on how to select an item with specific text if that item exists in two dropdowns. We need to be able to specify a custom data-test attribute for the dropdown-list inside of the popover so I have added a new attribute for ec-dropdown and ec-dropdown-search called `list-data-test`. This will allow us to do something like this in EBO:
```
<ec-dropdown
v-model="beneficiaryModel"
data-test="ebo-payees-information-beneficiaries-dropdown"
:list-data-test="`ebo-payees-information-beneficiaries-dropdown__item-list-${current …
```
> ONL-5777: feat: Add data-test for dropdown list.

- package-lock.json
- package.json
- src/components/ec-smart-table/ec-smart-table.spec.js
- src/components/ec-smart-table/ec-smart-table.story.js
- src/components/ec-smart-table/ec-smart-table.vue
`fetchArgs` will allow to add custom arguments into the `datasource.fetch()` call and also allow to reload the ec-smart-table every time these fetchArgs change. It doesn't add any new functionality but only exposes/uses the existing fetchArgs from withAbortableFetch HoC.
> ONL-2866: feat: Added fetchArgs prop for ec-smart-table.

- CONTRIBUTING.md
- package.json
This adds clarification when to create a tag.
Normally, `npm version` does that for us but we then loose the tag after squashing the commits when merging to master. There is a option in `npm version` called `no-git-tag-version` which should prevent creating a tag when bumping up the version, unfortunately, it also prevents the commit to be created -> bug.
> ONL-6216: docs: Better documentation about git tags and how to not loose them in every release

- src/hocs/ec-with-abortable-fetch/__snapshots__/ec-with-abortable-fetch.spec.js.snap
- src/hocs/ec-with-abortable-fetch/ec-with-abortable-fetch.js
- src/hocs/ec-with-abortable-fetch/ec-with-abortable-fetch.spec.js
The problem this solves is that I cannot wrap withAbortableFetch around EcCurrencyFilter because the data prop of EcCurrencyFilter is of type Array. withAbortableFetch passes `null` to that prop while loading the data and that throws an exceptions. Same problem is also with currenciesErrorMessage which expects string but withAbortableFetch passes a whole error object into it. This PR allows us to make corrections and transform the data when passing them from withAbortableFetch down to the wrapped component. 
The usage in EBO would look like this:
```
const EboAsyncCurrencyFilter = ecWithAbortableFetch(EcCurrencyFilter, {
dataProp: 'currencyItems',
loadingProp: 'isLoadingCurrencies',
errorProp: 'currenciesErrorMessage',
errorTransform: error => (error ? $gettext('Unable to retrieve list of …
```
> ONL-6219: feat: Added ability to pass custom transform fns to withAbortableFetch

- .eslintrc.js
- src/components/ec-inline-input-field/ec-inline-input-field.spec.js
- src/components/ec-multiple-values-selection/ec-multiple-values-selection.spec.js
- src/components/ec-table/ec-table.spec.js
- src/hocs/ec-with-abortable-fetch/ec-with-abortable-fetch.spec.js
- src/hocs/ec-with-filters/ec-with-filters.spec.js
We should not use async functions without await.
> ONL-6224: chore: Enabled require-await eslint rule.

- package-lock.json
- package.json
I didn't bump chameleon version when merged ONL-4998. This PR is only for doing that.
> ONL-4998: bump version

- package-lock.json
- package.json
- src/hocs/ec-with-abortable-fetch/__snapshots__/ec-with-abortable-fetch.spec.js.snap
- src/hocs/ec-with-abortable-fetch/ec-with-abortable-fetch.js
From now on, `this.fetchAbortController` and `this.isFetching` will be in the _try_ and _catch_ blocks. The _finally_ block is removed.
> [ONL-6386] Removing finally block in EcWithAbortableFetch

- package-lock.json
- package.json
- src/main.js
This allows us to get the `flatpickr.setDefaults` function in EBO.
> ONL-6464: chore: Expose flatpickr so we can access its setDefaults() method

- package-lock.json
- package.json
- src/components/ec-datepicker/__snapshots__/ec-datepicker.spec.js.snap
- src/components/ec-datepicker/ec-datepicker.spec.js
- src/components/ec-datepicker/ec-datepicker.vue
At the EcDatepicker component we have 3 types of disabled dates
- Days before min date limit and days after max date limit (we don't allow to type or select)
- Bank holidays/specific days (we don't allow to select)
- Weekends (we don't allow to select)
All 3 types should have a unified behavior and we should not be able to select them or directly type a disabled date.
When we type a disabled date it should default to an empty input.
This PR is for expanding the behavior that we currently have for min/max dates where we are not allow to type a disabled date to also cover the bank holidays and weekends.
> ONL-6465: Disable typing disabled dates

- src/components/ec-menu/__snapshots__/ec-menu.spec.js.snap
- src/components/ec-menu/ec-menu.vue
- src/components/ec-navigation-link/__snapshots__/ec-navigation-link.spec.js.snap
- src/components/ec-navigation-link/ec-navigation-link.spec.js
- src/components/ec-navigation-link/ec-navigation-link.vue
- tests/stubs/router-link.stub.js
- tests/stubs/router-view.stub.js
Removed `isExact` prop from navigation link because it's no longer supported by vue-router@4 (https://router.vuejs.org/api/index.html#router-link-props).
This prop existed in version 3 (https://v3.router.vuejs.org/api/#exact) but it's no longer needed because the exact class is now determined always by the router.
> [ONL-6745] Migrated ec-navigation-link

- .storybook/main.js
- package.json
When developing the fix for Main container responsivness, we have noticed that the styles in vercel preview has not been updated. It could be because webpack and babel cache everything on the filesystem in the node_modules. If vercel reuses the same node_modules for each build, it may not pick up changes done in the branch. This PR fixes that and disables the caching when running the production build.
This issue started after migrating Storybook to Webpack 5 when adding Vue 3.
> [ONL-6861] fix: Fixed webpack cache when deploying to prod.

- .circleci/config.yml
- package.json
- src/composables/use-ec-pagination/use-ec-pagination.spec.js
- src/composables/use-ec-sorting/use-ec-sorting.spec.js
- src/directives/ec-amount/ec-amount.spec.js
- src/utils/countdown.spec.js
- src/utils/mask.spec.js
When linting the code in Circle CI, we should always run them without fixing the errors. The linters should fail the build instead.
I have fixed all linting issues that have happened recently after dependabot updated some eslint dependencies. They were not reported by the build, but fixed.
Screenshot from master build shows that there are eslint errors but they were fixed instead:
> [ONL-6886] fix: Fixed linters in Circle CI are running in fix mode.

- package-lock.json
- package.json
- src/styles/settings/colors/colors.story.js
- src/styles/settings/colors/complementary-color-scale.css
- src/styles/settings/colors/index.css
- src/styles/themes/b-w.css
- src/styles/themes/blue.css
- src/styles/themes/green.css
- src/styles/themes/hotpink.css
- src/styles/themes/red.css
- tailwind.config.js
The Figma spec has another colors theme called complementary colors, those are only to pair them with key colors to create gradients. We use a gradient like this in the legacy code (login page) and now there's a requirement for the modern code (Cards).
Complementary colors are brandable but only 7 brands (all based on Ebury's base color) are going to have them set. Rest of the brands will use key-color-4 and key-color-2 as a backup if complementary colors are not specified (that's what legacy does too).
There will be another PR in EBO to populate `--ec-theme-complementary-color-level-1` and `--ec-theme-complementary-color-level-2` from brand settings. The goal is to be able use a new class `tw-bg-gradient-1` to produce the same gradient as in Figma.
Design link: …
> [ONL-6912] Added complementary colors to chameleon and gradients that are using them

- package-lock.json
- package.json
- src/components/ec-metroline/components/ec-metroline-item/ec-metroline-item.vue
- src/components/ec-metroline/ec-metroline.vue
- src/main.js
Added METROLINE_PROVIDE_KEY to main exports because it's needed in EBO tests.
> [ONL-6946] Fixed metroline using undefined as provide key.

- package-lock.json
- package.json
- tailwind.config.js
Allow constructing gradients using TW classes, e.g.
```html
<h1 class="tw-bg-gradient-to-r tw-from-key-3 tw-to-key-6 tw-text-key-7">Test</h1>
```
Produces:
and 
```
<h1 class="tw-bg-gradient-to-r tw-from-key-3 tw-to-key-6 tw-via-gray-4 tw-text-gray-7">Test</h1>
```
Produces:
> [ONL-7004] chore: Enabled gradient stop colors.

- package-lock.json
- package.json
- tailwind.config.js
An additional feature for gradients in chameleon, we need to be able to access gradient stop colors as individual classes (tw-stop-key-4) so they can be re-used in SVG gradients too.
> [ONL-7004] Expose stop-color as individual classes so they can be used inside SVGs.

- src/styles/elements/index.css
- src/styles/generic/index.css
- src/styles/settings/index.css
While investigating the ec-modal, I noticed that the footer in ec-modal is broken in SB (https://chameleon-ebury.vercel.app/iframe.html?args=large:true&id=modal--basic&viewMode=story)
The buttons no longer have box-sizing set to border-box but to content-box. All elements in the chameleon should inherit box-sizing from the parent, html should set it to border-box (elements.css):
```
html {
box-sizing: border-box;
}
*,
*:before,
*:after {
box-sizing: inherit;
}
```
^^ But this is no longer included in the generated CSS. Other bits from the `elements.css` are included but not this one. It turned out it's purgecss removing the styles for `html` very likely due to a change from vue/cli to vite which uses PostCSS very different way.
The first 3 layers of ITCSS shouldn't be purged at all as …
> [ONL-7016] fix: Prevent purgecss purging generic CSS.

- package-lock.json
- package.json
- src/components/ec-full-screen-overlay/ec-full-screen-overlay.vue
Currently when focus trap is enabled and we have an element like a dropdown inside the overlay, we won't be able to click on the items of the dropdown. 
Adding `allowOutsideClick: true` solves the issue.
> [ONL-7030] chore: allow outside click

- package-lock.json
- package.json
- src/components/ec-menu/ec-menu.vue
- src/main.js
Small change, specifies width to 100%. This gives context to the ellipsis and allows it to be triggered.
Before change
After change
ALSO
Small change on the name of the tooltip export
> [ONL-7096] fix: ellipsis on menu

- eslint/lib/rules/vue-props-interface.js
- eslint/tests/lib/rules/vue-props-interface.js
If we have the same props in vue file and in the types.ts but one extra prop in one of them, then ESLint rule doesn’t proceed with this situation as an error. We should consider this as an error.
> ONL-7256 Fix vue-props-interface rule for ESLint

- .storybook/main.js
- package-lock.json
- package.json
**Jira ticket:** [ONL-7455](https://fxsolutions.atlassian.net/browse/ONL-7455)
Install the  [`@vitejs/plugin-vue-jsx` package](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue-jsx) to add JSX support to Vue and also change Vite config in `.storybook/main.js` to use this new plugin instead of the Storybook default one (React JSX).
[ONL-7455]: https://fxsolutions.atlassian.net/browse/ONL-7455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ONL-7455] Fix broken JSX stories

- .eslintrc.js
- src/components/ec-alert/ec-alert.vue
- src/components/ec-amount-input/ec-amount-input.vue
- src/components/ec-btn/ec-btn.vue
- src/components/ec-checkbox/ec-checkbox.vue
- src/components/ec-datepicker/ec-datepicker.vue
- src/components/ec-dropdown-search/ec-dropdown-search.vue
- src/components/ec-dropdown/ec-dropdown.vue
- src/components/ec-input-field/ec-input-field.vue
- src/components/ec-metroline/ec-metroline.vue
- src/components/ec-navigation-link/ec-navigation-link.vue
- src/components/ec-panel/ec-panel.vue
- src/components/ec-phone-number-input/ec-phone-number-input.vue
- src/components/ec-popover/ec-popover.vue
- src/components/ec-radio-btn-group/ec-radio-btn-group.vue
- src/components/ec-radio-btn/ec-radio-btn.vue
- src/components/ec-table-filter/ec-table-filter.vue
- src/components/ec-table-pagination/ec-table-pagination.vue
- src/components/ec-textarea/ec-textarea.vue
There is an issue with Storybook because they are still using Vue 3.2.47, so the new `defineEmits` syntax is not being recognized by the controls and therefore we can't modify emits there because the events section is not being displayed.
> [ONL-7579] Refactor defineOptions and defineEmits

- src/components/ec-smart-table/ec-smart-table.spec.js
- src/components/ec-table/ec-table.spec.ts
- src/components/ec-table/ec-table.vue
During the migration to TS we removed `rowIndex`, but it shouldn't be removed as it is used to get bene ids on EBO
> [ONL-7921] Fix ec-table migration

- package-lock.json
- package.json
- src/components/ec-smart-table/__snapshots__/ec-smart-table.spec.js.snap
- src/components/ec-table/__snapshots__/ec-table.spec.ts.snap
- src/components/ec-table/ec-table.vue
Adding `table-layout: fixed;` to `ec-table` when custom rows are being shown
> **NOTE**
> In smart table preview there is a scroll caused by pagination. It will be solved when the new pagination responsive design is implemented
> [ONL-7971] Adjust table min width when card component is included

- package-lock.json
- package.json
- src/components/ec-smart-table/__snapshots__/ec-smart-table.spec.js.snap
- src/components/ec-smart-table/ec-smart-table.spec.js
- src/components/ec-smart-table/ec-smart-table.vue
It was not possible to update filters using the model from a parent component because it was not reacting to `filter` prop changes
> [ONL-8007] Fix ec-smart-table filter model reactivity

- package-lock.json
- package.json
- tailwind.config.js
Upgrade to TW3 introduced a problem with tw-grid not having negative margins anymore. It's because the `theme()` no longer supports negative values, so `theme(margin.${gutter / -2}),` doesn't render anything.
> [ONL-8008] Fixed TW grid negative margins.

- .github/dependabot.yml
This new feature should prevent dependabot to create lots of disconnected PRs, especially when upgrading packages that are interconnected like `@vueuse` or `@storybook`.
> [ONL-8121] Group dependabot updates

- .github/dependabot.yml
- package-lock.json
- package.json
- src/components/ec-icon/ec-icon.story.ts
- src/components/ec-inline-input-field/components/copy/copy.vue
- src/components/ec-inline-input-field/ec-inline-input-field.spec.ts
- tests/mocks/ec-tooltip.mock.ts
Replacing clipboard-copy library with implementation builtin in vueuse. There's no need to update EBO this time.
> [ONL-6699] Replaced clipboard-copy with useClipboard.

- package-lock.json
- package.json
- src/components/ec-popover/__snapshots__/ec-popover.spec.ts.snap
- src/components/ec-popover/ec-popover.spec.ts
- src/components/ec-popover/ec-popover.vue
- src/components/ec-popover/types.ts
We need 2 more props to be declared for ec-popover in order to migrate user-info component in EBO.
> [ONL-8262] Added missing props for popover.

- package-lock.json
- package.json
- src/components/ec-modal/ec-modal.spec.ts
- src/components/ec-modal/ec-modal.vue
Considering that modal should always trap the focus(as it is modal nature), even if ec-modal component somehow loses it, we add this continious activation of focusTrap to ensure that modal always traps focus back.
> [CHUX-295] Force ec-modal to trap focus

- src/components/ec-menu/__snapshots__/ec-menu.spec.ts.snap
- src/components/ec-menu/ec-menu.spec.ts
- src/components/ec-menu/ec-menu.vue
- src/components/ec-mobile-header/__snapshots__/ec-mobile-header.spec.ts.snap
- src/components/ec-mobile-header/ec-mobile-header.spec.ts
- src/components/ec-mobile-header/ec-mobile-header.vue
- src/components/ec-navigation-link/ec-navigation-link.vue
- src/components/ec-navigation/__snapshots__/ec-navigation.spec.ts.snap
- src/components/ec-navigation/ec-navigation.spec.ts
- src/components/ec-navigation/ec-navigation.vue
- src/main.ts
Adding mobile view for ec-navigation
> [CHUX-467] ec-navigation mobile view

- package-lock.json
- package.json
- src/components/ec-letter-icon/ec-letter-icon.spec.ts
- src/components/ec-letter-icon/ec-letter-icon.vue
- src/components/ec-letter-icon/types.ts
- src/main.ts
This is needed if we want to keep using good CSS practices in EBO, as it can be done by modifying the styles of the Chameleon component on EBO, but this approach is against best practices.
> [CHUX-661] Add prop to ec-letter-icon to control hover styles

- package-lock.json
- package.json
- src/components/ec-metroline/components/ec-metroline-item/ec-metroline-item.vue
- src/components/ec-mobile-header/__snapshots__/ec-mobile-header.spec.ts.snap
- src/components/ec-mobile-header/ec-mobile-header.vue
- src/components/ec-navigation/__snapshots__/ec-navigation.spec.ts.snap
- src/components/ec-navigation/ec-navigation.vue
- src/components/ec-panel/ec-panel.vue
- src/styles/components/ec-btn/ec-btn.css
In this PR
- Removing the max-width limitation of button components.
- Making the metroline CTA footer expand the full width on mobile devices. As a consequence this will also allow the cta items to expands as well to the full width. 
also
- fixing some BEM stuff
also
- setting up a z-index to ec-panel because mobile header is overlaying it
> [CHUX-690] Make metroline footer cta mobile friendly

- package-lock.json
- package.json
- src/components/ec-dropdown/__snapshots__/ec-dropdown.spec.ts.snap
- src/components/ec-dropdown/ec-dropdown.spec.ts
- src/components/ec-dropdown/ec-dropdown.story.ts
- src/components/ec-dropdown/ec-dropdown.vue
- src/components/ec-dropdown/types.ts
> [CHOPS-1424]  Add bottom note prop to dropdown

- package-lock.json
- package.json
- src/components/ec-navigation/__snapshots__/ec-navigation.spec.ts.snap
- src/components/ec-navigation/ec-navigation.spec.ts
- src/components/ec-navigation/ec-navigation.story.ts
- src/components/ec-navigation/ec-navigation.vue
- src/components/ec-navigation/types.ts
> [CHOPS-890]  Add optional logo link to homepage

- package-lock.json
- package.json
- src/components/ec-datepicker/ec-datepicker.vue
There seems to be an issue with the Flatpickr datetime component. 
As mentioned on their website https://flatpickr.js.org/mobile-support/, this created an issue where the EBO web app on a mobile view displayed 2 datepicker components instead of 1. 
Disabling mobile allows the web app to use the datepicker without the additional native datepicker.
> [CHOPS-1072] Adding disableMobile property for flatpickr

- package-lock.json
- package.json
- src/components/ec-smart-table-heading/types.ts
- src/components/ec-smart-table/ec-smart-table.story.ts
- src/components/ec-smart-table/ec-smart-table.vue
- src/components/ec-smart-table/types.ts
- src/components/ec-table-head/ec-table-head.spec.ts
- src/components/ec-table-head/ec-table-head.vue
- src/components/ec-table-head/types.ts
- src/components/ec-table/ec-table.spec.ts
- src/components/ec-table/ec-table.story.ts
- src/components/ec-table/ec-table.vue
- src/components/ec-table/types.ts
Updating the smart-table, table and heading components to allow adding an optional column that contains checkboxes to select things in the table. We should also be able to pass an `isSelectableCheck` function so that we can filter which rows can be selectable. 
** changes to onRowClick behaviour - the `onRowClick` fn should only be called when clicking anywhere in the row besides the checkbox cell - we usually want to open up a details panel when clicking on the row and this makes sure that selecting a row won't also open up that panel.
Using the new props in the activity log table (new Neyes functionality) - without passing `isSelectableCheck`:
Using `isSelectableCheck` so only the changes in the table that have a status of 'pending your approval' can be selected:
Check out this PR …
> [NBL-480]: Update table components to support multi selection

- package-lock.json
- package.json
This PR prepares for the release of `v2.8.24`
> [CHOPS-2159] chore: prepare release v.2.8.24
